/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface NetworkSpawnerFields {
  local?: boolean
  noUpnp?: boolean
  rootDir?: string | undefined | null
  size?: number
}
/** A spawner for creating local SAFE networks for testing and development. */
export declare class NetworkSpawner {
  constructor(args?: NetworkSpawnerFields | undefined | null)
}
