/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface BootstrapConfigFields {
  backwardsCompatibleWrites?: boolean
  cacheDir?: string
  cacheSaveScalingFactor?: number
  disableCacheWriting?: boolean
  disableCacheReading?: boolean
  disableEnvPeers?: boolean
  first?: boolean
  initialPeers?: Array<string>
  local?: boolean
  maxCachedPeers?: number
  maxAddrsPerCachedPeer?: number
  minCacheSaveDurationMs?: number
  maxCacheSaveDurationMs?: number
  networkContactsUrl?: Array<string>
}
export interface NetworkSpawnerFields {
  /**
   * NOTE: Currently dead code - not read by constructor.
   * The EVM network is passed via a separate `network` parameter.
   * TODO: Future cleanup should read this field instead for consistency.
   */
  evmNetwork?: string
  rewardsAddress?: string
  noUpnp?: boolean
  rootDir?: string | undefined | null
  size?: number
  bootstrapConfig?: BootstrapConfigFields
}
export interface NodeSpawnerFields {
  /**
   * NOTE: Currently dead code - not read by constructor.
   * The EVM network is passed via a separate `network` parameter.
   * TODO: Future cleanup should read this field instead for consistency.
   */
  evmNetwork?: string
  socketAddr?: string
  rewardsAddress?: string
  noUpnp?: boolean
  rootDir?: string | undefined | null
  bootstrapConfig?: BootstrapConfigFields
}
export declare class SwarmLocalState {
  get connectedPeers(): Array<string>
  get peersInRoutingTable(): number
  get listeners(): Array<string>
}
/** Once a node is started and running, the user obtains a NodeRunning object which can be used to interact with it. */
export declare class RunningNode {
  /** Returns this node's `PeerId` */
  peerId(): string
  /**
   * Returns the root directory path for the node.
   *
   * This will either be a value defined by the user, or a default location, plus the peer ID
   * appended. The default location is platform specific:
   *  - Linux: $HOME/.local/share/autonomi/node/<peer-id>
   *  - macOS: $HOME/Library/Application Support/autonomi/node/<peer-id>
   *  - Windows: C:\Users\<username>\AppData\Roaming\autonomi
  ode\<peer-id>
   */
  rootDirPath(): string
  /** Returns a `SwarmLocalState` with some information obtained from swarm's local state. */
  getSwarmLocalState(): Promise<SwarmLocalState>
  /** Return the node's listening addresses. */
  getListenAddrs(): Promise<Array<string>>
  /** Return the node's listening addresses with the peer id appended. */
  getListenAddrsWithPeerId(): Promise<Array<string>>
  /** Return the node's listening port */
  getNodeListeningPort(): Promise<number>
  /** Returns the list of all the RecordKeys held by the node */
  getAllRecordAddresses(): Promise<Array<Array<number>>>
  /** Returns the node's reward address */
  rewardAddress(): Array<number>
  /** Shutdown the SwarmDriver loop and the node (NetworkEvents) loop. */
  shutdown(): void
}
/** Represents a running test network. */
export declare class RunningNetwork {
  /** Returns a bootstrap peer from this network. */
  bootstrapPeer(): Promise<string>
  /** Returns a bootstrap peer from this network. */
  runningNodes(): Promise<Array<RunningNode>>
  /** Shutdown all running nodes. */
  shutdown(): Promise<void>
}
/** A spawner for creating local SAFE networks for testing and development. */
export declare class NetworkSpawner {
  constructor(args?: NetworkSpawnerFields | undefined | null, network?: Network | undefined | null)
  /** Spawns the network with the configured parameters. */
  spawn(): Promise<RunningNetwork>
}
/** A spawner for creating local SAFE networks for testing and development. */
export declare class NodeSpawner {
  constructor(args?: NodeSpawnerFields | undefined | null, network?: Network | undefined | null)
  /** Spawns the network with the configured parameters. */
  spawn(): Promise<RunningNode>
}
export declare class Network {
  constructor(local: boolean)
  static fromString(name: string): Network
}
/**
 * A local EVM testnet for development and testing.
 *
 * Starts an Anvil node and deploys the required smart contracts.
 * Requires Anvil to be installed (via Foundry).
 */
export declare class Testnet {
  /**
   * Creates and starts a new local EVM testnet.
   *
   * This starts an Anvil node and deploys:
   * - Network token contract
   * - Data payments contract
   * - Merkle payments contract
   */
  static new(): Promise<Testnet>
  /**
   * Returns the Network configuration for this testnet.
   * Use this with NetworkSpawner to spawn nodes connected to this EVM.
   */
  toNetwork(): Network
  /**
   * Returns the default wallet private key (from Anvil's first account).
   * This wallet has pre-funded ETH for testing.
   */
  defaultWalletPrivateKey(): string
  /** Returns the RPC URL of the local Anvil node. */
  rpcUrl(): string
}
